[package]
name = "isabelle"
version = "0.1.0"
authors = ["Brendon Roberto <Brendon.Roberto@hyland.com>"]
edition = "2018"

[dependencies]
serenity = "0.8"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
